### ISSUE TITLE
[PROPOSAL] Rename porter-homebrew to homebrew-porter

### ISSUE THREAD

**Issue by iennae** [deislabs/homebrew-porter#5]
Rename project from porter-homebrew to homebrew-porter.

Based on the documentation on https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md it seems like this project should be called homebrew-porter so that the short tap can be used instead.

**Comment by carolynvs** [comment]
Oh I'm so glad you are jumping on this one. It would be great to have porter on homebrew!

Let me rename the repo, I didn't realize that I had the name backwards.

**Comment by carolynvs** [comment]
Done!
